name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source mi_entorno/bin/activate
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: |
          source mi_entorno/bin/activate
          flake8 .

      - name: Start Flask server
        run: |
          source mi_entorno/bin/activate
          nohup python run.py --host=0.0.0.0 --port=5000 &
          sleep 10  # Espera 10 segundos para que el servidor se inicie

      - name: Test with pytest
        run: |
          source mi_entorno/bin/activate
          pytest

      - name: Security check with Bandit
        run: |
          source mi_entorno/bin/activate
          bandit -r app

      - name: Dependency check with Safety
        run: |
          source mi_entorno/bin/activate
          safety check --ignore 70612
